fredlcore/BSB-LAN

BSB_lan.ino

Move block to display the IP after the initiation WiFi or Ethernet,
correct Ethernet start to make DHCP possible

Correct DHCP

---

BSB_lan.ino
BSB_lan_config.h.default

Added support for a DNS server which is different from the subnet's gateway.

Added support for separate DNS server

---

BSB_lan.ino

Save some bytes.

---

BSB_lan.ino

Revert "Small bug correction"

---

BSB_lan.ino

Small change to store BSB_VERSION only once

move BSB_VERSION to PROGMEM

---

BSB_lan.ino

I had some issue on Windows (putty) using DebugTelnet, when disconnecting causing BSB-LAN to freeze (website was not loading at all, only ping was working)

fix unresponsive website when terminating telnet session

---

BSB_lan.ino

Debug: 
1. JSON broken when user set empty lists. https://github.com/fredlcore/bsb_lan/issues/91#issuecomment-632908688
2. lost date and uptime values in datalog.

JSON broken. lost date and uptime values in datalog.

---

BSB_lan.ino
localization/create-undefs.pl

JSON format for localization. Code cleanup for /JI command.

JSON localization, /JI optimization

---

BSB_lan.ino

remove _printFIXPOINT function overloading

Fast fix for _printFIXPOINT

---

BSB_lan_config.h.default

authentification comes from french it's somewhat correct but authentication is better.

Fix spelling

---

BSB_lan.ino

Automatic creation of datalog.txt on startup if it is not present on the SD card

Automatic creation of datalog.txt

---

BSB_lan.ino

/JA command added (print 24h average values in JSON)
Bugfix in deprecated function: Writing outside the array

/JA command

---

BSB_lan.ino

Query for 20000-20200 still break MQTT i mean

fast fix for https://github.com/fredlcore/bsb_lan/issues/157

---

BSB_lan.ino

Fix #157 
@dukess Any opinion on this fix?

MQTTPayload exists only if MQTT_JSON is defined

---

.github/workflows/platformio.yaml
tests/config/BSB_lan_config_default.h
tests/config/BSB_lan_config_mqtt.h
tests/config/BSB_lan_config_mqtt_json.h

To spot a bug like #157 before a user notices it :)
CI is expected to fail until #161 is merged

[CI] Try to compile with MQTT and MQTT JSON

---

BSB_lan.ino
BSB_lan_EEPROMconfig.h
BSB_lan_config.h.default
BSB_lan_defs.h
tests/config/BSB_lan_config_default.h
tests/config/BSB_lan_config_mqtt.h

Bug fixes:
Board can't start with static IP now. Fixed.
UseEEPROM moved to config file. UseEEPROM = 0 can be used for fallback startup. Do not forget update config file.
Wrong info about logging and interval on config page.
Known issues:
Mega 2560 board: if program size more than ~245000 bytes you can got error "avrdude: verification error, first mismatch at byte 0x3c000"
WEBCONFIG module doesn't  work at this time on Mega:
C:\Users\User\AppData\Local\Temp\ccuOzsoN.s:115706: Error: value of 72118 too large for field of 2 bytes at 112281
C:\Users\User\AppData\Local\Temp\ccuOzsoN.s:115849: Error: value of 72118 too large for field of 2 bytes at 112468

Bugfixes after revolution

---

.gitignore
BSB_lan.ino
BSB_lan_defs.h

Bugfix: DS18B20 programs with temperature values not shown
Source of troule: violation of the sorting order in cmdtbl

Bugfix: DS18B20 programs with temperature values not shown

---

BSB_lan.ino
BSB_lan_defs.h

Revert back to two cmdtbls because 3 tables not work on Mega for unknown reason.
Fallback init with predefined room unit type added

Revert back to two cmdtbls

---

BSB_lan.ino
BSB_lan_EEPROMconfig.h
BSB_lan_config.h.default
BSB_lan_defs.h
localization/LANG_DE.h

CF_LOGCURRINTERVAL_TEXT now "Log interval, seconds"
Handlers added for applying settings on the fly or reboot where it need
Not tested on devices

Handlers for applying settings on the fly

---

BSB_lan.ino

Bugfix for issue https://github.com/fredlcore/bsb_lan/issues/170

remove leading spaces via MQTT #170

---

BSB_lan.ino

https://github.com/fredlcore/bsb_lan/issues/196

Killing undead QAA_TYPE value.

---

BSB_lan.ino
BSB_lan_config.h.default
html_strings.h

you can add #define I_WILL_USE_EXTERNAL_INTERFACE to config file for saving space (~6..8Kb). /DG command will be disabled

Code reduction #2. Option I_WILL_USE_EXTERNAL_INTERFACE  to disable /DG

---

BSB_lan.ino

Will return potential precision (incrementing step) for DT_VALS type values: 1, 0.1, 0.01, 0.001, 0.00001

Additional JSON filed "precision"

---

BSB_lan.ino

More complexity parsing of structure of incoming JSON message: values can be strings or numbers.
Multiple JSON messages in a single request (/JS) allowed
Need test

Bugfix for https://github.com/fredlcore/bsb_lan/issues/217

---

BSB_lan.ino
BSB_lan_defs.h

as I supposed previons version not working. At least for Mega. Fixed.

Improvement for Mega

---

BSB_lan.ino
localization/LANG_RU.h

rename reset() to queryDefaultValue().
Need to change MENU_TEXT_ER3

 rename reset() to queryDefaultValue() 

---

BSB_lan.ino
BSB_lan_defs.h
localization/LANG_DE.h

custom_float and custom_long can be displayed or modified through programs 20700-20799 and 20800-20899

custom_float and custom_long I/O through virtual programs

---

BSB_lan.ino
src/BSB/bsb.cpp
src/BSB/bsb.h

This patch adds basic support for ESP32 boards. Tested on Olimex ESP32-POE, but others should work too.

Support for ESP32 Boards

---

localization/LANG_FR.h

Translate the most common states of the boiler into French

Lang: improve French

---

BSB_LAN/BSB_LAN.ino
BSB_LAN/BSB_LAN_defs.h
BSB_LAN/localization/LANG_RU.h

Fix: address of pointer -> pointer
Static definition of arrays of floats.
ARM -> __arm__
Cosmetic changes: 
custom_float and custom_longs will be enumerate from 1 not 0 in Category 49
"Raumthermostat 3" now use ENUM not SWITCH.

Fixes and cosmetic changes

---

BSB_LAN/html_strings.h

Just insert piece of code from https://github.com/dukess/bsb_lan_ajax/blob/master/ajax.html

Display grid on chart

---

openapi.yaml

Just smaller things and i found /JI is providing more info than i thought

Update API doc

---

BSB_LAN/BSB_LAN.ino

when programWriteMode == 2 we return true when FL_RONLY flag is set

changing programIsreadOnly() behavior

---

BSB_LAN/BSB_LAN.ino
BSB_LAN/BSB_LAN_defs.h

Oh, one more thing: functions tables sizes was corrected for Mega users.

code readability, reducing the number of sensors programs setup points

---

BSB_LAN/BSB_LAN.ino

https://github.com/fredlcore/BSB-LAN/discussions/267#discussioncomment-3328323

bugfix for JSON format for /JB command

---

BSB_LAN/BSB_LAN.ino
BSB_LAN/BSB_LAN_EEPROMconfig.h
BSB_LAN/BSB_LAN_config.h.default
BSB_LAN/localization/LANG_DE.h

c.f. https://github.com/fredlcore/BSB-LAN/issues/432
tested:
- logging to: none, SD, UDP, SD+UDP
- on ESP32, via WiFi
not tested:
- logging to: MQTT, averages (don't know how to receive/interpret)
- on Arduino, via LAN (not available)

Optional logging via UDP broadcast added (configurable, same parameters and format as in SD card logging)

---

BSB_LAN/BSB_LAN.ino
BSB_LAN/src/esp32_time.h

Fix for https://github.com/fredlcore/BSB-LAN/issues/515
Adaptive (int/float) program numbers printing for /Q command
Fix for wrong month and weekday numbers

Set of fixes

---

BSB_LAN/BSB_LAN.ino

fixed: rounding bug (roundf()->(int)() was reverted).
fixed: bug with additional program number printing

Fix for night commit

---

BSB_LAN/src/esp32_time.h

Fix for https://github.com/fredlcore/BSB-LAN/issues/527

fix for wrong day of month

---

BSB_LAN/BSB_LAN.ino
BSB_LAN/BSB_LAN_config.h.default
BSB_LAN/include/get_cmdtbl_values.h

This option will dramatically slow down MCU performance. Useful for developers not for users.

DEVELOPER_DEBUG - Very verbose debug output

---

BSB_LAN/include/print_webpage.h

Fixes https://github.com/fredlcore/BSB-LAN/issues/533, at least on my system.

Buffer overrun fix in version check on home page

---

BSB_LAN/html_strings.h
BSB_LAN/scripts/BSB-LAN_datalog-viewer.html

Revert "/DG fix for logs spanning resets"

---

BSB_LAN/html_strings.h
BSB_LAN/scripts/BSB-LAN_datalog-viewer.html

Revert "Revert "/DG fix for logs spanning resets""

---

BSB_LAN/html_strings.h

removing some left-overs from an earlier version
This PR here shouldn't affect functionality.
It only makes the code more understandable to me, as it removes stuff that has now become unneccessary.
Sorry for not noticing this before https://github.com/fredlcore/BSB-LAN/pull/542 got merged!

/DG code cleanup

---

BSB_LAN/html_strings.h
BSB_LAN/scripts/BSB-LAN_datalog-viewer.html

c.f. https://github.com/fredlcore/BSB-LAN/issues/539#issuecomment-1478477386 ff

Avoid gaps in /DG plots

---

BSB_LAN/scripts/combine_datalogs.pl
BSB_LAN/scripts/create_datalog_index.pl

Provide tools for offline datalog manipulation

---

BSB_LAN/BSB_LAN.ino
BSB_LAN/BSB_LAN_EEPROMconfig.h
BSB_LAN/BSB_LAN_config.h.default
BSB_LAN/include/mqtt_handler.h
BSB_LAN/include/print2webclient.h
BSB_LAN/include/print_ipwe.h

Some bugfixes for destination addresses output
Fix for parameter size calculation
parameter.dest_addr is 'short' now instead 'int'. Some bytes will be saved in EEPROM

Changing type of *_parameters arrays from 'float + float' to 'parameter'

---

BSB_LAN/include/mqtt_handler.h

* On connection lost, do not try to reconnect immediately, it will likely fail
* Don't block main loop while trying to reconnect
* Prefer bool over boolean
Relates to https://github.com/fredlcore/BSB-LAN/issues/638
Hanging for 3 * 1s
```
Connected to MQTT broker, updating will topic
Subscribed to topic 'BSB2'
Published status 'online' to topic 'BSB2/status'
[ 38796][D][WiFiClient.cpp:536] connected(): Disconnected: RES: 0, ERR: 128
Client ID: BSB-LAN2
Will topic: BSB2/status
[ 38797][E][WiFiGeneric.cpp:1584] hostByName(): DNS Failed for 
Failed to connect to MQTT broker, retrying...
[ 39801][E][WiFiGeneric.cpp:1584] hostByName(): DNS Failed for 
Failed to connect to MQTT broker, retrying...
[ 40801][E][WiFiGeneric.cpp:1584] hostByName(): DNS Failed for 
Failed to connect to MQTT broker, …
```

Don't hang on MQTT connection attempt

---

BSB_LAN/scripts/BSB-LAN_datalog-viewer.html

To re-synchronize the look with https://github.com/fredlcore/BSB-LAN/pull/645

Added BSB-LAN watermark to offline datalog viewer
