- html_strings.h
Viewport für Handys hinzugefügt.
Mit diesem Meta Tag wird der Zoom der Website automatisch auf das Handy Display angepasst.
Added viewport for mobile devices.
With this meta tag the zoom of the website is automatically adjusted to the mobile device's display.
> Viewport für Handys hinzugefügt / Added viewport for mobile devices

- BSB_lan.ino
- BSB_lan_defs.h
VT_ONOFF, VT_YESNO, VT_CLOSEDOPEN, VT_VOLTAGEONOFF got "isswitch" flag for JSON and enums instead strings -> code much cleaner
old bug (pre-0.44): Error messages (category #32) not shown correctly. ENUM_ERROR was assigned to every "empty" VT_ERRORCODE .
query() function was splitted as in "revolution" but with backward compatibility.
Web interface: time output in func Nr 500-616 was corrected.
> improvements: time output in func Nr 500-616, old bug in category #32

- BSB_lan.ino
Bugfix: unknown JSON commands hanging the program;
Bugfix for JSON: wrong data type was returned with /JQ command when we got error 7.
Code changed:
Parameter searching in printTelegram() was "splitted" for two parts: 1. For defined parameter numbers - binary search; 2. For undefined parameter number (-1) - sequential search as before.
It will increase perfomance for QUERY and SET operations.
Code cleanup:
sprintf()->sprintf_P(), on advice of @loetmeister in https://github.com/fredlcore/bsb_lan/issues/102
client.print() -> bufferedprint();
> Bugfixes in JSON, speedup

- BSB_lan.ino
- localization/LANG_RU.h
JSON bugfix: number of categories was hardcoded as 42. Now is set as CAT_UNKNOWN.
> JSON bugfix: last six caregories not shown

- BSB_lan_config.h.default
I guess it makes sense to use the same subnet as default here as you do for all other network config defaults?
> use 192.168.178 subnet in default mqtt config

- BSB_lan.ino
- BSB_lan_EEPROMconfig.h
Small optimizations
Check pattern ((^|,)((\d){1,5}))for config page added
unused field was kicked out from configuration_struct
Dynamic reconfiguration of MAX_CUL client.
MQTT JSON fields naming.
Bugfix:  MQTT JSON sends empty wrapper without content  when log_parameters[i] == 0
>  MAX_CUL client, MQTT JSON fix

- BSB_lan.ino
- BSB_lan_EEPROMconfig.h
- BSB_lan_defs.h
- localization/LANG_DE.h
- localization/LANG_RU.h
Now is three states here:
0 - all programs is read-only.
1 - all programs is writable except read-only and OEM
2 - all programs is writable except read-only
WARNING: "read-only" behavior is inverted after upgrade. Check setting.
> Enhanced software-controlled writing values to programs

- BSB_lan.ino
- BSB_lan_EEPROMconfig.h
Note: I change pattern for EEPROM erasing from 0x00 to 0xFF for testing on "new" EEPROMs and with PPS settings. 
For issue https://github.com/fredlcore/bsb_lan/issues/196
> Bugfix: hanging on new EEPROM

- BSB_lan.ino
Very interesting:
char sscanf_buf[24];
strcpy_P(sscanf_buf, PSTR("%u.%u.%u.%u"));
sscanf(buf, sscanf_buf, &i0, &i1, &i2, &i3);
is shorter than
sscanf_P(buf, PSTR("%u.%u.%u.%u"), &i0, &i1, &i2, &i3);
> save 98 bytes of RAM

- BSB_lan.ino
- json-api-version.h
/JV comamnd for JSON API version added. Payload: {"api_version": "major.minor"}
strncasecmp() replaced with strncmp_P()
New file added: json-api-version.h
> JSON API version

- BSB_lan.ino
- BSB_lan_EEPROMconfig.h
/JL command:
"id" field was renamed to "parameter"
"type" now is integer
"format" now is integer
> /JL command: "id" field renamed to "parameter"

- BSB_lan_config.h.default
It was added recently, but undefine referring to wrong define meant that MDNS still took space on Mega2560 by default.
With custom defs optimization and this change there was enough space to also fit MQTT in my case without changing anything else - good result.
> Fix MDNS_HOSTNAME undefine

- BSB_lan.ino
The check against the trusted IP Addresses did a direct memory
comparison, which is dependent on compiler and memory layout.
Changed the implementation to use the overloaded == operator from
IPAddress.h, which works regardless of this. Note, that != is not
overloaded, hence the explicit negation, != wouldn't work.
> Fix trusted_ip check

- BSB_LAN/BSB_LAN.ino
-new option for query parameters from heater via MQTT
-all the code wich is for sending mqtt-messages came in a new function mqtt_sendtoBroker
(this code was not changed except log_parameters[i] to param)
-sending ACK to broker moved prior set-command (it looks better in the log, when first ACK and then the result)
-after set-command run mqtt_sendtoBroker to send new value immediately
Now I hope, this PR runs better as my first...
> improve options for MQTT

- BSB_LAN/BSB_LAN.ino
This PR adds a [last will/status](https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/) topic handling. This way, we always have the current state of the MQTT device available at the broker. Tools like Home Assistant (HA) use this to determine, if the integration in question is available or currently down. The will/status subtopic used is "status" below the configured prefix, f.x. "BSB-LAN/status". Values can be "online" and "offline". 
To make this easier, I took the liberty to refactor the code a bit:
Improved the mqtt_connect code. We allocate a bit less RAM on each call (as we're connected almost all of the time). When connecting, we register our last will & testament at the status topic. After a successful connection, we update the status topic to online and …
> Mqtt last will topic handling & code improvements

- BSB_LAN/BSB_LAN_defs.h
Correct command codes for programs numbers 5 and 6 for Baxi Luna Platinum+ (Should be used via INF).
P.S. I've never paid attention to it, but today I decided to check it out, and it turned out that it needs to be fixed.
> Summer time for Baxi Luna Platinum+

- .github/workflows/platformio-esp32.yaml
- BSB_LAN/BSB_LAN.ino
- BSB_LAN/include/mqtt_handler.h
- BSB_LAN/include/print2webclient.h
- BSB_LAN/include/print_ipwe.h
- BSB_LAN/src/esp32_time.h
Fix for Issue https://github.com/fredlcore/BSB-LAN/issues/513
Adaptive (int/float) program numbers printing for web interface, MQTT, UDP/file logging.
Due: callback for SdFat library added for setup correct timestamps on log files.
ESP32: TimeLib library wrapper added. This wrapper can't be used with TimeLib in same time on ESP32. Wrapper will allow to set correct timestamps on log files.
> Fix for Issue #513. Correct timestamps for log files. Fix for new SdFat

- BSB_LAN/include/mqtt_handler.h
An exception was thrown after publishing a json message in mqtt_mode 3. Apparently a buffer overlow in outBuf was responsible for the exception, since it did not happen for mqtt_mode 1 or 2, where the messages are significantly shorter. The refactored function mqtt_sendtoBroker() is not using outBuf anymore.
Also in the buffer overflow protection of function mqtt_callback(...) 4 bytes were reserved for creating the acknowledgement message from the original message, but 5 bytes are needed (4 for the ACK_ prefix and one for the terminating nul character).
This pull request is fixing issue #520
> Fixes in mqtt_handler.h

- BSB_LAN/BSB_LAN.ino
"%.1f" was replaced with "%g". Code more readable, shorter (and faster?). Thanks to @DE-cr 
roundf() was replaced with (int)() where is it possible.
Fix for /JC and /JK commands (additional condition in printToWebClient_prognrdescaddr() may block parameter name printing) 
Tested on ESP32.
> replacing "%.1f" with "%g". Fix  for /JC and ?JK commands

- BSB_LAN/BSB_LAN.ino
Using a category number outside the valid range would set cat_min and cat_max to arbitrary numbers and produce all kinds of crazy behaviour.
The category number is now checked before the array ENUM_CAT_NR is referenced and in case of an illegal category number 0 is used.
> Fixed code for Web API /JK=<category-number>

- BSB_LAN/BSB_LAN.ino
... if available from the heap, otherwise falling back to the existing static (<=) 1 KB buffer
reason: performance improvement (>20% on an esp32 w/o SD card, using wifi)
An equivalent algorithm is already part of my https://github.com/fredlcore/BSB-LAN/pull/542, but only for /Dyyyy-mm-dd,YYYY-MM-DD, as /D and /Dn in that PR use transmitFile() directly (and therefore would also benefit from this PR here!).
The change has been done based on measuring /D times [s] on a datalog.txt of about 970 KB on my system (see above), comparing implementations using the original 1 KB buffer size and the new 4 KB buffer size for the transfer (file reading and data transmission over http):
```
1 KB   4 KB   gain       
----+------+------+-----
#1    7.09   5.12   28 %
#2    6.92   5.18   25 %
#3    6.86 …
```
> Use 4 KB buffer in transmitFile() on ESP32

- BSB_LAN/BSB_LAN.ino
- becomes relevant once year rolls over
- affects /DG, which uses /Da,b
- requires re-building of datalog.idx (e.g. via /D0)!
I am _so_ sorry that I didn't catch this before https://github.com/fredlcore/BSB-LAN/pull/542 was merged!
I thought I had done enough testing then, but as it turns out, I should have used the target platform for that, not some other little-endian system. :/
Before merging, could you please run the following sketch on an Arduino and check if the hex numbers in its output are all in ascending order? (I've done this test for esp32.)
```
typedef union {
struct { uint8_t day, month; uint16_t year; } elements;  // order is important here!
uint32_t combined;
} compactDate_t;
void f(int d, int m, int y) {
char s[99];
compactDate_t date;
sprintf(s,"%02d.%02d.%04d => …
```
> Bug fix for /Da,b

- BSB_LAN/BSB_LAN.ino
- get rid of empty ", ,"s in /C output of compiled modules (c.f. https://github.com/fredlcore/BSB-LAN/pull/575)
- add missing PSTR() in one cleanupDatalog() return (c.f. https://github.com/fredlcore/BSB-LAN/pull/572#pullrequestreview-1416522992)
- add comment regarding bigBuffer double use in /D... code (c.f. https://github.com/fredlcore/BSB-LAN/commit/844c16c7d1adc4d5119572600645ab9f0b777207#commitcomment-112489758)
> Compiled modules list cosmetics etc

- BSB_LAN/BSB_LAN.ino
I always need a calculator to convert long ms values to `d+h:m:s`
With this PR in place, I don't:
> Make uptime in /C more legible

- BSB_LAN/BSB_LAN.ino
...at least for potentially long lasting actions, e.g. /D or /K24.
This avoids unnecessarily blocking bsb-lan for other tasks (including new client requests).
Succesfully tested on ESP32 with wifi connection, using the url commands given above.
I consider this ready for merging.
> Stop serving client that is already gone

- BSB_LAN/BSB_LAN.ino
as already proposed in https://github.com/DE-cr/BSB-LAN/commit/7c37e987bab2c421463be78f965bf837e1dc9ba9#commitcomment-132716175
tested on my system (ESP32), considered ready to be merged
> /C: include current date/time for all systems

- BSB_LAN/BSB_LAN_EEPROMconfig.h
- BSB_LAN/localization/LANG_DE.h
- BSB_LAN/localization/LANG_EN.h
With reference to https://github.com/fredlcore/BSB-LAN/issues/632#issuecomment-1999089017
Moved storage location config to general section, as it applies for both logging and webserver file system.
**Please note: I don't know if this requires additional measures to address possible shifts in EEPROM storage locations!**
Changed some GUI strings to address SD card vs. flash memory ambiguity.
Removed "ESP32" from GUI string for energy saving, as other ESP32 only strings don't have that prefix either (OTA, SD/flash).
Adjusted whitespace in one code area, so that comments properly align regardless of tab width setting.
> Change some GUI strings to address SD card vs. flash memory ambiguity

- BSB_LAN/html_strings.h
Tested with Firefox (Ubuntu), Chromium (Ubuntu), Chrome (Android), Silk (Android), Edge (Win11), Safari (Mac)
(It would have been much easier if the favicon was a light enough color right away: `.c3{background:url('favicon.svg')no-repeat center}`.)
> Add BSB-LAN watermark to /DG chart

- BSB_LAN/scripts/BSB-LAN_datalog-viewer.html
Contrary to the BSB-LAN executable, we don't use an existing black svg here, but are creating our own one. Therefore we don't have to go through hoops to achieve opacity; we can just render the svg lighter.
Sorry for not thinking of this while https://github.com/fredlcore/BSB-LAN/pull/647 was still open.
Feel free to ignore this change proposal and just close the PR.
> Simplify code in BSB-LAN_datalog-viewer.html

- BSB_LAN/html_strings.h
- BSB_LAN/scripts/BSB-LAN_datalog-viewer.html
notes:
the subchart only becomes visible when zooming in on the chart
the subchart's gray area can be moved to move the zoom window
helpful subchart side effect: when zoomed in, de-/selecting curves doesn't zoom out, as it does w/o a subchart
to get rid of the subchart: reload /DG
before the code change:
with the code change:
> /DG: added rescaling and subchart on zooming

- BSB_LAN/src/PubSubClient/README.md
- BSB_LAN/src/PubSubClient/library.json
- BSB_LAN/src/PubSubClient/library.properties
The original devlopers forgot to do this, but fixed it a day after we merged the #683.
This PR is documentation and consistency only.
> Update the PubSubClient version numbers and documentation in its root folder

- BSB_LAN/include/mqtt_handler.h
This PR fixes a problem in the MQTT connection code. The problem exists since long time and seem to not affect ESP32, but on Arduino Due for some reason the malloc allocated `tempstr` is destroyed when freed and then the hostname saved in the PubSubClient is therefore corrupted (random bytes at beginning). You can also see this if the log message on serial console contains wrong bytes at beginning of hostname.
As the size of `tempstr` is known from the beginning (it is known at compile time), the whole malloc/free can be removed and instead a static on-stack buffer be used. This also reduces fragmentation of heap.
The only downside is that after the method exists, a pointer to the on-stack buffer is still referenced from the pubsubclient instance. But as it is only required while …
> Fix "use after free" in setup of hostname for MQTT connection

- BSB_LAN/include/mqtt_handler.h
Hi @fredlcore,
this is just something I found out while reviewing the code yesterday in PR #717: It adapts the buffersize for creating the topic (for listening on) in the same way like I have done yesterday for the hostname. As before, the sizeof is evaluated by the compiler, so compiled code is identical.
It is up to you to merge this although it fixes no real bug, but it makes the code more safe when modifying config file to larger topic buffer size and it is easier to read.
Uwe
> Adapt the size of MQTT tempTopic to the size of config variable

- BSB_LAN/include/print_webpage.h
I was confused about how to use OTA to upload the .bin file, and I'm sure I'll forget again sometime in the future, so I added a little helper link right next to the version string. Would this be a useful addition? Never mind if it isn't. 🤭
> Add OTA link to homepage
